### ISSUE TITLE
README note on ion-content childeScope

### ISSUE THREAD

**Issue by jpgilchrist** [Urigo/meteor-ionic#22]
@Urigo, as requested:

Please add to the README a note about using meteor-ionic, meteor-angular-ui-router, and angular-meteor. 

Routes:
``` javascript
$stateProvider
  .state('myState', {
    url: '/mystate',
    template: UiRouter.template('mystate.hmtl'),
    controller: 'MyStateCtrl'
  });
```

Template:
``` html
<template name="mystate.html">
  <ion-view tile="My State">
    <ion-content class="has-header has-footer">
      <form>
        <input type="text" ng-model="myVar"/>
        <button type="submit" ng-click="updateMyVar(myVar)">Update myVar</button>
      </form>
      [[ myVar ]]
    </ion-content>
  </ion-view>
</template>
```

Controller:
``` javascript
angular.module("MyApp", ['angular-meteor', 'ui-router', 'ionic'])
  .controller("MyStateCtrl", [ '$scope', function($scope) {
    $scope.updateMyVar = function(value) {
      console.log("Value: " + value);
      $scope.myVar = "";
    }
  });
```

You'll notice that the proper value will be logged to the console. However, the bound data in the template `[[ myVar ]]` is still the value you entered in the input[text]. And does not get reset back to "" as you defined it in the controller. 

The issue is that `<ion-content>` directive uses it's own childScope (http://ionicframework.com/docs/api/directive/ionContent/). Therefore, the scope variable defined in ng-model is applied on the childScope, *not the scope of your controller*. Therefore, you must use `$parent` when defining a variable in ng-model in order to have the proper scoping!

New Template:
``` html
<template name="mystate.html">
  <ion-view tile="My State">
    <ion-content class="has-header has-footer">
      <form>
        <input type="text" ng-model="$parent.myVar"/>
        <button type="submit" ng-click="updateMyVar($parent.myVar)">Update myVar</button>
      </form>
      [[ $parent.myVar ]]
    </ion-content>
  </ion-view>
</template>
```

This will work as expected.

**Comment by Urigo** [comment]
We can close this now that we don't need meteor-angular-ui-router with the new [urigo:angular 0.6.0 version](https://github.com/Urigo/angular-meteor/releases/tag/0.6.0)
