### ISSUE TITLE
Updating the project to Meteor 1.0 not working on iOS

### ISSUE THREAD

**Issue by Xample** [Urigo/meteor-ionic#24]
Download the example file at https://codeload.github.com/netanelgilad/meteor-ionic-example/zip/master
Then:
```bash
cd ~/Downloads/meteor-ionic-example-master
meteor update
meteor add-platform ios
meteor run ios
```
The app starts but gets stuck on the splash screen.
![screen shot 2014-11-16 at 19 16 46](https://cloud.githubusercontent.com/assets/944605/5061891/242f0764-6dc5-11e4-8941-0f6887f04822.png)

**Comment by davidyaha** [comment]
add this to mobile-config.js:
    App.setPreference('AutoHideSplashScreen' ,'true');

**Comment by Urigo** [comment]
@netanelgilad can you add this to the example so we can close this?

**Comment by Urigo** [comment]
Added to the example, closing
