### ISSUE TITLE
Not All Ionicons Available

### ISSUE THREAD

**Issue by panthongw** [Urigo/meteor-ionic#33]
Some icons are rendering (ion-checkmark, ion-help, ion-compose) and some are not (ion-ios-list, ion-ios-paper), so I am wondering if this package includes all the icons from Ionicons?

If I have to include them myself could you please point me to some resources.

Thanks

**Comment by Urigo** [comment]
Hi, thank you for the question.

Are those Icons from the 2.0 version?  if so, that might be the reason:
https://github.com/driftyco/ionic/issues/2679

**Comment by panthongw** [comment]
Hi Urigo, The icons I mentioned are not from 2.0, but was part of the iOS naming convention change. It seems like a fix should be coming out for 2.0. Thanks

**Comment by Urigo** [comment]
OK, hopefully we could add it soon.

**Comment by panthongw** [comment]
Looks like the the Ionicon update is on master. driftyco/ionic#2679

**Comment by Urigo** [comment]
@panthongw got that working in the new version.
Please re-open if persists

**Comment by panthongw** [comment]
@Urigo I am using package v0.3.0 and I tried to update one of my tab with `ion-ios-list`, but nothing was displayed. Are the icons something I have to update myself?

It is the same code on the (panlist) [https://github.com/panthongw/panlist] repo.

Thanks

**Comment by Urigo** [comment]
Have you checked with the regular Ionic?
I've updated to their latest version from master (not the beta14 release)

**Comment by panw** [comment]
Looks like it is on master
https://github.com/driftyco/ionic/commit/6f50c87ec36ff1b12fdb3a762933c3efaa60c297

From the looks of it master is also using beta14
https://github.com/driftyco/ionic/blob/master/package.json

**Comment by Urigo** [comment]
@panw you right. it wasn't really the latest, my mistake.
Now it suppose to be fixed.

**Comment by panw** [comment]
@Urigo I might not have been getting the updates. For some reason when I did `meteor update` it did not update the package, so I have been on v0.3.0. Only when I did `meteor add urigo:ionic@0.4.0` did it update it. This might be a Meteor bug. Sorry about the confusion.

Did you run into this issue?

**Comment by Urigo** [comment]
no..  but I've also just released the new version now so maybe it took some time to be updated everywhere...
