### ISSUE TITLE
Uncaught TypeError: Cannot read property '$$minErr' of undefinedangular-sanitize.js:8 (anonymous function)angular-sanitize.js:680

### ISSUE THREAD

**Issue by brugnara** [Urigo/meteor-ionic#35]
In a meteor project without angular, I'm getting this error in browser console.

Thanks for your work.

**Comment by fix** [comment]
same here

**Comment by ndevr** [comment]
add urigo:angular

**Comment by ndevr** [comment]
if you are using angular-ui-router add the package mquandalle:bower too. With bower add "angular-ui-router": "~0.2.13" and it should be work. Please note that the bower package has some issues with loading order - loading ionic with bower is impossible because of that issue.

**Comment by brugnara** [comment]
But the documentation says I can use this without angular.

**Comment by ndevr** [comment]
theres a weak dependency... don't know how it works, but without adding angular it's not working for me

**Comment by ndevr** [comment]
Looks like it would be easier to add just the http://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js + css :+1:

**Comment by ndevr** [comment]
Be sure angular is loaded at first. 

.meteor/packages

urigo:angular
urigo:ionic
urigo:angular-google-maps

**Comment by ndevr** [comment]
#37 could be interesting for you as well

**Comment by Urigo** [comment]
You don't have to use angular-meteor, but you do have to use AngularJS, Ionic is dependent on that.
You can bring it in anyway you want.
I've just released a new version and also updated the readme to explain that here - https://github.com/Urigo/meteor-ionic/commit/7dccd08c3d0e0fb6593cb174cb5d59ea3e05c1aa
