### ISSUE TITLE
Inconsistencies with Ionic

### ISSUE THREAD

**Issue by ndevr** [Urigo/meteor-ionic#37]
I have found out that the framework does not work properly. Especially the "collectionRepeat" Directive (http://ionicframework.com/docs/api/directive/collectionRepeat/) is not working correct anymore. Got a lot of flicker when i scoll up and down and I can't use smooth touch-scrolling anymore. I've created a repo https://github.com/ndevr/meteor-ionic-collection-repeat with the example of ionic's collection repeat demo where you can see the issues. I already forked "urigo:angular" to test it with angular 1.3.6 cause ionic using it in the bundle of the latest version (v1.0.0-beta-14) and your package is using 1.3.8. I'am not sure what is wrong but it looks like angular did some wrong calculations for positioning?! I really need the directive because of the performance problems with large lists.

**Comment by ndevr** [comment]
Could fix it with setting the correct dependencies: https://github.com/ndevr/meteor-ionic/commit/0e67206b6fa9b0ea86c005b99b58a5d5e3d23722

**Comment by Urigo** [comment]
Done in 0.3.0, please re-open in case you have trouble
