### ISSUE TITLE
Template Variables Treated As Strings

### ISSUE THREAD

**Issue by panthongw** [Urigo/meteor-ionic#38]
I am using the latest package (v0.3.0) and the template variables, such as `[[post.title]]` and `[[post.description]]`, are treated as strings instead of the variable value. 

My setup is using a tab view and below are the details:

```
Posts = new Mongo.Collection("posts");

angular.module('app', ['angular-meteor', 'ui.router', 'ionic'])

.controller('PostCtrl', ['$scope', '$meteorCollection', '$state', '$ionicModal',
  function ($scope, $meteorCollection, $state, $ionicModal) {
    $scope.Posts = $meteorCollection(Posts);
}])

.config(['$stateProvider', '$urlRouterProvider',
function($stateProvider, $urlRouterProvider){
  $urlRouterProvider.otherwise('/');

  $stateProvider
.state('tabs', {
    url: '/tab',
    abstract: true,
    views: {
      main: {
        templateUrl: 'tabs.html'
      }
    }

  })

  .state('tabs.feed', {
    url: '/feed',
    views: {
      feed: {
        templateUrl: 'feed.html',
        controller: 'PostCtrl'
      }
    }
  })

  .state('tabs.help', {
    url: '/help',
    views: {
      help: {
        templateUrl: 'help.html'
      }
    }
  })
}])
```

Here are the relevant templates (`feed.html`, `tabs.html`):
```
<template name="feed.html">
  <ion-view title="Feed">
    <ion-nav-buttons side="right">
      <button class="button button-icon icon ion-compose" ng-click="openNewPostModal()"></button>
    </ion-nav-buttons>
    <ion-content class="has-header">
      <ion-list>
        <ion-item ng-repeat="post in Posts">
          <h2>[[post.title]]</h2>
          <p>[[post.description]]</p>
        </ion-item>
      </ion-list>
    </ion-content>
  </ion-view>
</template>
```

```
<template name="tabs.html">
  <ion-tabs class="tabs-positive">
    <ion-tab icon="ion-checkmark" ui-sref="tabs.feed">
      <ion-nav-view name="feed"></ion-nav-view>
    </ion-tab>
    <ion-tab icon="ion-help" ui-sref="tabs.help">
      <ion-nav-view name="help"></ion-nav-view>
    </ion-tab>
  </ion-tabs>
</template>

```

Looking at the [Meteor-ionic-example] (https://github.com/netanelgilad/meteor-ionic-example), I notice that `ng-include` is being used with `tpl` files. Based on my setup, I cannot use ng-include and would prefer to define my template in the router. 

I have tried the following with the necessary changes (curly braces instead of square, removed `template name=".."`, renamed file to `tpl`), which did not work:
```
.state('tabs.feed', {
    url: '/feed',
    views: {
      feed: {
        templateUrl: '"feed.tpl"',
        controller: 'PostCtrl'
      }
    }
  })
```

Could you please provide me with any guidance on how I could update the app with the current tab setup.

Thanks

**Comment by Urigo** [comment]
@panthongw yes you are right.
I've just updated the example and the readme so reflect the way you need to initialize your app:

https://github.com/Urigo/meteor-ionic/commit/96b79a3f59ada1cbdcded0a99659a715b901d2fd

Tell me if it helped you

**Comment by panthongw** [comment]
@Urigo thanks for your response and that helps! 

My initial post was not very clear, but I updated to hopefully better reflect my problem. The issue I am reporting is in regards to template variables not being interpreted and instead treated as strings.

This might be an issue with Ionic not registering the `PostCtrl`. Could you please have a look and let me know. 

Thank you

**Comment by Urigo** [comment]
ohhhhh I see,
now there is no reason to use - [[ something ]] anymore, you can just put your template files with .tpl ending and use the regular {{ something }}

**Comment by panthongw** [comment]
I tried different things, but was not successful. I added you as a collaborator to the project. Could you check it out when you get a chance and point me in the correct direction.

Thanks

**Comment by Urigo** [comment]
@panthongw your repo has been fixed.
I charge by the hour ;)

Hope it helped

**Comment by panthongw** [comment]
@Urigo Thanks a lot for the help. Noticed you are one of the speakers for the next SF Meetup. I would be happy to get you coffee or something then :)

**Comment by Urigo** [comment]
Cool!  see you then
