### ISSUE TITLE
add this as Cordova only package

### ISSUE THREAD

**Issue by AhmadEl-Banna** [Urigo/meteor-ionic#43]
Hi there , I'm new to meteor and I'm trying to build a system with mobile client and web client,both have completely different look and feel and requirements,
is there any way to add this magnificent package for cordova only ,and add say bootstrap or material design for the browser .
I know that I can download the code and change the package.js to add the files on cordova only but then I have to do it every time you guys push an update .
any Ideas 
Thank you

**Comment by Urigo** [comment]
so you should check out this example - https://github.com/idanwe/meetup-NY-ionic-chat
which uses meteor-client-side Bower package: https://github.com/idanwe/meteor-client-side

**Comment by AhmadEl-Banna** [comment]
Cool , Thank you very much
