### ISSUE TITLE
Ionic doesn't init if index and meteorionic swapped

### ISSUE THREAD

**Issue by phaggood** [Urigo/meteor-ionic#45]
I'm trying to figure out how to make the meteorionic starter app more like ionic - normally the ion-nav-view goes into index.html and all other pages are inserted into index.html via the router. If I try to correct this in the sample, ionic does not initalize and none of my pages will show up (and of course, it fails silently).  Here's a link to the meteorionic starter done up like the tutorial which works fine up until I swap out ui-view with ion-nav-view.

https://drive.google.com/file/d/0B9cUKQX6oSyGWFlPOVlNQjBMREU/view?usp=sharing

**Comment by Urigo** [comment]
@phaggood can you share it as a Github repo please?

**Comment by Urigo** [comment]
closing as there is no reproduction
