### ISSUE TITLE
Ionic view

### ISSUE THREAD

**Issue by babakness** [Urigo/meteor-ionic#46]
I would be great to have an example/pattern on how to share an app published either to Galaxy/Meteor server or privately using Ionic View!

http://view.ionic.io

**Comment by MilosStanic** [comment]
+1

**Comment by Urigo** [comment]
so you should check out this example - https://github.com/idanwe/meetup-NY-ionic-chat
which uses meteor-client-side Bower package: https://github.com/idanwe/meteor-client-side
