### ISSUE TITLE
ionic tabs not work good!

### ISSUE THREAD

**Issue by train860** [Urigo/meteor-ionic#48]
Hi,
when I click the tab,it comes to be this!and errors in the chrome console!
thank you for help!
![image](https://cloud.githubusercontent.com/assets/6874537/8175220/9f4eb052-1419-11e5-9efa-245775a4ac38.png)

**Comment by babakness** [comment]
I've had a pull request to fix this for like a week.

https://github.com/Urigo/meteor-ionic/pull/47

The package's dependencies need to be updated.

**Comment by train860** [comment]
@babakness thank you！

**Comment by Urigo** [comment]
Addressed here:  https://github.com/Urigo/meteor-ionic/pull/47#issuecomment-113951360

@train860 if you just do 

    meteor update

for now, does it work?

**Comment by train860** [comment]
@Urigo thank you for response!
I use "meteor update",but error happened.information is here：

While downloading angular:angular@1.4.1...:
error: socket hang up

so，I change to a new project，use “meteor add urigo:angular”。I works，but the version is a older one：urigo:angular    0.8.12* 

cannot use “meteor add urigo:angular” to get the latest version？

**Comment by Urigo** [comment]
@train860 very strange... looks like a network error no?

**Comment by Urigo** [comment]
@babakness did `meteor update` worked for you?

**Comment by train860** [comment]
@Urigo should be network error！but，why cannot get the latest version by meteor add

**Comment by Urigo** [comment]
I guess that's happens when you add urigo:ionic before urigo:angular?

If that's the case the reason is that Meteor's version solver takes the lowest possible versions that is supported by the rest of the packages.

Can you try loading urigo:angular as the first package of the app and see if it is still takes an older version?

**Comment by train860** [comment]
Yep!I get the last version of urigo:angular,but the same error happen……

Is it because of my angular:angular-animate  package version？

![54550bc4-acc4-43a5-b4cf-6c97e08046d8](https://cloud.githubusercontent.com/assets/6874537/8320927/12c9f00c-1a53-11e5-8c0e-ea6694297e52.png)
![dd67c5a8-afc7-49a3-acdf-29dcc55f1e9b](https://cloud.githubusercontent.com/assets/6874537/8320931/2464e6fa-1a53-11e5-89cc-11f74cca75a2.png)
![89334bcc-1926-44b1-805e-a60d9da8cd70](https://cloud.githubusercontent.com/assets/6874537/8320941/35f983d0-1a53-11e5-9dac-30880e58b979.png)

**Comment by train860** [comment]
I have  resolved this problem by update angular:angular-animate and angular:angular-sanitize to the last version directly！

thank you very much！

**Comment by Urigo** [comment]
Yes I can see why, When for the version solver, specifying a version means that's the highest version that that package was tested with.
I"ll merge the pull request and release a new version later today.
@train860 and @babakness , thank you

**Comment by Urigo** [comment]
Released 1.0.0_1 with updated dependencies, can you check this out?

**Comment by train860** [comment]
I works now! nice work!!!
