### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by diego-vieira** [Urigo/meteor-ionic#58]
@Urigo as you mentioned at [https://github.com/driftyco/ionic/pull/3133] is there a blog post on how to integrate ionic + meteor + angular-meteor already?

Thanks

**Comment by Urigo** [comment]
Yes!
One with the Meteor build process: https://twitter.com/meteorjs/status/655066914897723392
and one with the Ionic CLI: https://twitter.com/Ionicframework/status/655066658508247040
